language: go
go:
  - 1.6.2
sudo: required
dist: trusty
before_install:
  - go get github.com/golang/lint/golint
before_script:
  - go get -d ./...
script:
  - ./scripts/licensecheck.sh
  - go build ./...
  - ./scripts/golint.sh
  - go vet ./...
  - sudo apt-get update
  - sudo apt-get install -y libvirt0 libvirt-bin qemu
  - sudo virsh version
  - sudo go test -v -tags=integration ./...
